# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Yank • Library / yEAh Network
email: admin@yeahgames
description: > # this means to ignore newlines until "baseurl:"
  The official Yank of yEAh Games library archive collection. Learn about The Yank, how to get started, and view the latest updates on all stuff finance-related.
  
  
#baseurl: "/cards" # the subpath of your site, e.g. /blog
url: "https://yankarchive.yeahgames.net" # the base hostname & protocol for your site

#sidebar
default-image: https://cdn.yeahgames.net/img/branding/logos/text/red.png # If there is no featured image in a post then this image will be showed. Also on all pages this image will be showed. Use a 500x250 image.

#footer

built-by: The yEAh Games Corporation, LLC.

copyright:
   name: The yEAh Games Corporation, LLC.
   link: 'https://yeahgames.net'

# Build settings
permalink: /item/:title/
paginate: 9
paginate_path: /page:num/

# Tracker
analytics: UA-83979019-1

# Comments

#social
facebook:
quora:
twitter: http://twitter.com/yEAhGames_
github: http://github.com/yEAh-Games
email: admin@yeahgames.net


# Sass style
sass:
  style: compressed

# Ruby Gems
plugins: 
  - jekyll-paginate
  - jekyll-seo-tag

collection:
   name: Yank Archive
   link: '//yankarchive.yeahgames.net'

owner:
   name: The Yank of yEAh Games
   link: '//yank.yeahgames.net'

